---
# tasks file for facts
- name: include assert.yml
  include_tasks: assert.yml
  run_once: yes

- name: create ansible facts directory
  file:
    path: /etc/ansible/facts.d
    state: directory
    mode: "0755"

- name: place custom facts
  template:
    src: "facts.j2"
    dest: /etc/ansible/facts.d/custom.fact
    mode: "0644"
  notify: setup
